# Generated by Django 4.2.13 on 2024-06-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_phone_number', models.CharField(max_length=50)),
                ('host_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_card.eventdetails')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_card.hostdetails')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_card.messagedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
