# Generated by Django 4.2.13 on 2024-06-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issuer_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CVResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.certification')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('graduation_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal_info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('responsibilities', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.language')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.personalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='languages',
            field=models.ManyToManyField(through='cv_resume.PersonalLanguage', to='cv_resume.language'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.cvresume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.skill')),
            ],
        ),
        migrations.AddField(
            model_name='cvresume',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.education'),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.personalinfo'),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='prifile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_resume.profilephoto'),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='skills',
            field=models.ManyToManyField(through='cv_resume.CVSkill', to='cv_resume.skill'),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.workexperience'),
        ),
    ]
